### ISSUE TITLE
get root()

### ISSUE THREAD

**Issue by D-a-n-i-l-o** [katyukha/thepath#6]
Is there a better way to get the root of the path than ´Path.current.segements.front´?
Also, ´Path.current.segments´ can‘t be indexed using ´[0]´ or ´[1]´?

Can you please add ´.root()´ to get the root dir/drive, additional to the check ˋ.isRoot()´?
It should return ´/´ or ´C:\´ or ´//´ or something like that. The root of the absolute, expanded (~) path.

**Comment by amlel-el-mahrouss** [comment]
We also must consider network drives (\\\\.Mac\\\\Desktop).

**Comment by katyukha** [comment]
Hi!

I just have released new version 1.2.0 of this lib.
It now contains new method `driveName` that will return drive name of the path (if any). It should solve the issue.

About `segments`, it uses `std.path.pathSplitter` from standard library, that produces range, thus it cannot be indexed, but as workaround you can use `front` as you mentiond, or if you want to work with result as with array, you can convert it to array via `Path.current.segments.array`
